### ISSUE TITLE
Namesake

### ISSUE THREAD

**Issue by AlexBrunetti** [Joel-Baptista/YACE#1]
Hello,
please note that YACE has been already used for a note chess engine; please consider to choose a different one, to avoid confusion.

https://www.chessprogramming.org/Yace

Alex

**Comment by Joel-Baptista** [comment]
Hello @AlexBrunetti,

I wasn’t aware of this preexisting chess engine, but I agree that I should change the name of this repository to avoid any confusion.

Thank you for bringing this to my attention!
